@echo off
echo Starting Karkhana Software Factory Output...
echo Booting Next.js Frontend...
start cmd /k "cd frontend && npm install && npm run dev"
echo Booting FastAPI Backend...
start cmd /k "cd backend && python -m venv venv && call venv\Scripts\activate && pip install -r requirements.txt && uvicorn app.main:app --reload"
echo All systems go!
